if(EXISTS "/mnt/c/programowanie-zaawansowane/merge-sort/runTests[1]_tests.cmake")
  include("/mnt/c/programowanie-zaawansowane/merge-sort/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
