add_test([=[SortArrayTest.AlreadySorted]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.AlreadySorted]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.AlreadySorted]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.ReverseSorted]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.ReverseSorted]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.ReverseSorted]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.RandomArray]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.RandomArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.RandomArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.NegativeNumbers]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.NegativeNumbers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.NegativeNumbers]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.MixedNumbers]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.MixedNumbers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.MixedNumbers]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.EmptyArray]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.EmptyArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.EmptyArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.SingleElement]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.SingleElement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.SingleElement]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.Duplicates]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.Duplicates]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.Duplicates]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.NegativeDuplicates]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.NegativeDuplicates]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.NegativeDuplicates]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.MixedDuplicates]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.MixedDuplicates]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.MixedDuplicates]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.TwoElements]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.TwoElements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.TwoElements]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.LargeArray]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.LargeArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.LargeArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.LargeMixedArray]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.LargeMixedArray]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.LargeMixedArray]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SortArrayTest.LettersInsteadOfNumbers]=]  /mnt/c/programowanie-zaawansowane/merge-sort/build/test/runTests [==[--gtest_filter=SortArrayTest.LettersInsteadOfNumbers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SortArrayTest.LettersInsteadOfNumbers]=]  PROPERTIES WORKING_DIRECTORY /mnt/c/programowanie-zaawansowane/merge-sort SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_TESTS SortArrayTest.AlreadySorted SortArrayTest.ReverseSorted SortArrayTest.RandomArray SortArrayTest.NegativeNumbers SortArrayTest.MixedNumbers SortArrayTest.EmptyArray SortArrayTest.SingleElement SortArrayTest.Duplicates SortArrayTest.NegativeDuplicates SortArrayTest.MixedDuplicates SortArrayTest.TwoElements SortArrayTest.LargeArray SortArrayTest.LargeMixedArray SortArrayTest.LettersInsteadOfNumbers)
